contextId=contextid
contextData=contextdata
contextIdType=contextidtype
rootOrgId=rootorgid
profileDetails=profiledetails
contextid=contextId
contextidtype=contextIdType
contextdata=contextData
isarchived=isArchived